### ISSUE TITLE
Add ability to create Access Policy Key Vaults

### ISSUE THREAD

**Issue by phx-tim-butters** [Azure/terraform-azurerm-avm-res-keyvault-vault#84] opened 2024-03-08 16:16 UTC
For the purpose of Disk Encryption Sets, creating Key Vaults using the AVM is not possible as enable_rbac_authorization is statically set in the module itself.

Propose adding this as a variable.

**Comment by matt-FFFFFF** [comment] 2024-03-20 14:30
Duplicate of #60

**Closed by matt-FFFFFF** 2024-03-20 14:30 UTC
